// Copyright (c) 2026 Georgia Kaye O'Sullivan, NZ Aotearoa. All rights reserved.
// Use of this source code is prohibited except with explicit written permission from the author.

#ifndef FORM_LABELS_UI_H
#define FORM_LABELS_UI_H

#include <string> 

extern const std::string Employment_Type_Label;
extern const std::string Employee_Label;
extern const std::string Approximate_Annual_Salary_Label;
extern const std::string Contracted_Hours_Label;
extern const std::string Hourly_Rate_Label;
extern const std::string Contracted_Hourly_Rate_Label;
extern const std::string Monthly_Label;
extern const std::string Fortnightly_Label;
extern const std::string Weekly_Label;
extern const std::string Weekly_Hours_Label;
extern const std::string Annual_Salary_Label;
extern const std::string Monthly_Salary_Label;
extern const std::string Fortnightly_Salary_Label;
extern const std::string Weekly_Salary_Label;
extern const std::string Contracted_Weekly_Salary_Label;
extern const std::string Contracted_Fortnightly_Salary_Label;
extern const std::string Contracted_Monthly_Salary_Label;
extern const std::string Contracted_Annual_Salary_Label;
extern const std::string Contracted_Weekly_Hours_Label;
extern const std::string Overtime_Maximum_Label;
extern const std::string Overtime_Rate_Label;
extern const std::string Overtime_Maximum_Hours_Label;
extern const std::string Full_Time_Employment_Type_Label;
extern const std::string Part_Time_Employment_Type_Label;
extern const std::string Fixed_Term_Employment_Type_Label;
extern const std::string Single_Occasion_Employment_Type_Label;
extern const std::string KiwiSaver_Employer_Contribution_Label;
extern const std::string KiwiSaver_Employee_Contribution_Label;
extern const std::string Annual_Leave_Entitlement_Label;
extern const std::string Sick_Leave_Entitlement_Label;
extern const std::string Public_Holidays_Entitlement_Label;
extern const std::string Parental_Leave_Entitlement_Label;
extern const std::string Special_Leave_Entitlement_Label;
extern const std::string Superannuation_Contribution_Label;
extern const std::string Health_Insurance_Contribution_Label;
extern const std::string Professional_Development_Contribution_Label;
extern const std::string Employee_Assistance_Program_Contribution_Label;
extern const std::string Maternity_Leave_Entitlement_Label;
extern const std::string Paternity_Leave_Entitlement_Label;
extern const std::string Adoption_Leave_Entitlement_Label;
extern const std::string Shared_Parental_Leave_Entitlement_Label;
extern const std::string PAYE_Table_Version_Label;
extern const std::string PAYE_Extra_Voluntary_Deductions_Label;
extern const std::string PAYE_Frequency_Label;

// Personal Detail Labels
extern const std::string Address_Label;
extern const std::string First_Name_Label;
extern const std::string Middle_Name_Label;
extern const std::string Last_Name_Label;
extern const std::string Date_of_Birth_Label;
extern const std::string House_Number_Label;
extern const std::string Street_Name_Label;
extern const std::string Suburb_Label;
extern const std::string City_Label;
extern const std::string Postcode_Label;
extern const std::string Post_Box_Label;
extern const std::string Email_Address_Label;
extern const std::string Phone_Number_Label;

// Account Credential Labels
extern const std::string Username_Label;
extern const std::string Password_Label;
// Shared UI message labels
extern const std::string Unknown_Label;
extern const std::string IRD_Number_Label;
extern const std::string Tax_Information_Capitalized_Label;
extern const std::string IRD_Confirmation_Status_Label;
extern const std::string Please_Select_an_Option_Label;
extern const std::string Yes_No_Question_Input_Label;
extern const std::string Role_Type_Label_Admin;
extern const std::string Role_Type_Label_Finance;
extern const std::string Role_Type_Label_Trade;
extern const std::string Salary_Label;
extern const std::string Hourly_Label;
extern const std::string Casual_Label;
extern const std::string Junior_General_Administrator_Role_Label;
extern const std::string Senior_General_Administrator_Role_Label;
extern const std::string Junior_Trainee_Administrator_Role_Label;
extern const std::string Senior_Trainee_Administrator_Role_Label;
extern const std::string Junior_Casual_Administrator_Role_Label;
extern const std::string Senior_Casual_Administrator_Role_Label;
extern const std::string Admin_Receptionist;
extern const std::string Admin_Call_Centre_Operator;
extern const std::string Admin_Executive_Assistant;
extern const std::string Admin_Personal_Assistant;
extern const std::string Admin_Human_Resources;
extern const std::string Junior_IT_Support_Administrator_Role_Label;
extern const std::string Senior_IT_Support_Administrator_Role_Label;
extern const std::string Admin_Junior_Manager;
extern const std::string Admin_Senior_Manager;
extern const std::string Junior_General_Finance_Staff_Member;
extern const std::string Senior_General_Finance_Staff_Member;
extern const std::string Junior_Trainee_Finance_Staff_Member;
extern const std::string Senior_Trainee_Finance_Staff_Member;
extern const std::string Junior_Casual_Finance_Staff_Member;
extern const std::string Senior_Casual_Finance_Staff_Member;
extern const std::string Payroll_Administrator;
extern const std::string Accounts_Payable_Administrator;
extern const std::string Accounts_Receivable_Administrator;
extern const std::string Junior_Finance_Manager;
extern const std::string Senior_Finance_Manager;
extern const std::string Junior_General_Trade_Staff_Member;
extern const std::string Senior_General_Trade_Staff_Member;
extern const std::string Junior_Trainee_Trade_Staff_Member;
extern const std::string Senior_Trainee_Trade_Staff_Member;
extern const std::string Junior_Casual_Trade_Staff_Member;
extern const std::string Senior_Casual_Trade_Staff_Member;
extern const std::string Junior_Apprentice;
extern const std::string Senior_Mentor;
extern const std::string Safety_Officer;
extern const std::string Sales_Representative;
extern const std::string Junior_Trade_Manager;
extern const std::string Senior_Trade_Manager;

// View Accounts UI Labels
extern const std::string Account_Type_Label;
extern const std::string Business_Department_Label;
extern const std::string Job_Role_Label;
extern const std::string Admin_Accounts_Label;
extern const std::string Finance_Accounts_Label;
extern const std::string Trade_Accounts_Label;
extern const std::string Details_Menu_Question_Label;
extern const std::string Current_User_Account_Label;
extern const std::string Selected_User_Account_Label;
extern const std::string Select_Account_Prompt_Label;
extern const std::string Return_to_Previous_Menu_Label;
extern const std::string Return_to_Dashboard_Main_Menu_Label;
extern const std::string Return_to_Admin_Dashboard_Main_Menu_Label;
extern const std::string Return_to_Employee_Dashboard_Main_Menu_Label;
extern const std::string Return_to_Account_Management_Menu_Label;
extern const std::string Return_to_Account_Management_Main_Menu_Label;
extern const std::string Return_to_Employee_Management_Main_Menu_Label;
extern const std::string Return_to_Employee_Record_Edit_Options_Label;
extern const std::string Return_to_HR_Management_Main_Menu_Label;

// Employee Details UI Labels
extern const std::string Emergency_Contact_Label;
extern const std::string Diagnosed_Health_Conditions_Label;
extern const std::string Allergies_Label;
extern const std::string Approved_Emergency_Steps_and_Medicines_Label; // eg insulin can be given by those with first aid training
extern const std::string Prior_Training_and_Qualifications_Label;
extern const std::string First_Aid_Certification_Label;
extern const std::string Certified_Label;
extern const std::string Uncertified_Label;

// HR Management UI Labels
extern const std::string Pay_Period_Label;
extern const std::string Pay_Frequency_Label;
extern const std::string Pay_Type_Label;
extern const std::string Pay_Date_Label;
extern const std::string Total_Hours_Worked_Label;
extern const std::string Employee_Name_Label;
extern const std::string Employee_IRD_Number_Label;
extern const std::string ACC_Levy_Type_Label;
extern const std::string ACC_Earners_Levy_Label;
extern const std::string ACC_Earners_Levy_Rate_Label;
extern const std::string ACC_Workplace_Levy_Label;
extern const std::string ACC_Workplace_Levy_Rate_Label;
extern const std::string ACC_Levy_Maximum_Earnings_Threshold_Label;
extern const std::string Student_Loan_Repayment_Label;
extern const std::string Child_Support_Deduction_Label;
extern const std::string Child_Support_Status_Label;
extern const std::string Child_Support_Standard_Deduction_Label;
extern const std::string Child_Support_Voluntary_Deduction_Label;
extern const std::string Child_Support_Protected_Net_Earnings_Label;
extern const std::string Child_Support_Shortfall_Calculation_Label;
extern const std::string Child_Support_IRD_Notice_of_Deduction_Existence_Label;
extern const std::string Child_Support_IRD_Notice_of_Deduction_Amount_Label;
extern const std::string Child_Support_IRD_Notice_of_Deduction_Effective_Date_Label;
extern const std::string Child_Support_IRD_Notice_of_Deduction_Expiry_Date_Label;
extern const std::string Child_Support_IRD_Notice_of_Deduction_Reference_Number_Label;
extern const std::string ESCT_Existence_Label;
extern const std::string ESCT_Tax_Rate_Label;
extern const std::string ESCT_Income_Band_Label;
extern const std::string KiwiSaver_Opt_In_Out_Status_Label;
extern const std::string KiwiSaver_Employee_Contribution_Rate_Label;
extern const std::string KiwiSaver_Employee_Contribution_Rate_Options_Examples;
extern const std::string KiwiSaver_Employer_Contribution_Rate_Label;
extern const std::string KiwiSaver_Opt_Out_Date_Label;
extern const std::string Student_Loan_Existence_Label;
extern const std::string Student_Loan_Tax_Code_Label;
extern const std::string Student_Loan_Default_Rate_Label;
extern const std::string Student_Loan_SDR_IRD_Letter_Existence_Label;
extern const std::string Student_Loan_Special_Deduction_Rate_Label;
extern const std::string Student_Loan_Repayment_Exemption_Existence_Label;
extern const std::string Student_Loan_Repayment_Exemption_Reason_Label;
extern const std::string Student_Loan_Repayment_Exemption_Expiry_Date_Label;
extern const std::string Student_Loan_Repayment_Threshold_Label;
extern const std::string Student_Loan_Repayment_Rate_Label;
// General Tax Codes UI Labels
extern const std::string Tax_Codes_Label;
extern const std::string Tax_Codes_Job_Type_Label;
// Primary Tax Codes Labels
extern const std::string Primary_Tax_Code_Label;
extern const std::string M_Standard_Label;
extern const std::string ME_Standard_No_Student_Loan_Label;
extern const std::string SL_Student_Loan_Label;
// Secondary Tax Codes Labels
extern const std::string Secondary_Tax_Code_Label;
extern const std::string SB_Secondary_Low_Bracket_Label;
extern const std::string S_Secondary_Standard_Label;
extern const std::string SH_Secondary_Higher_Bracket_Label;
extern const std::string ST_Secondary_Top_Bracket_Label;
extern const std::string SA_Secondary_Additional_Top_Bracket_Label;
extern const std::string Special_Tax_Code_Label;
// STC Special Tax Code (requires IRD letter)
extern const std::string STC_Special_Tax_Code_Label;
extern const std::string STC_Rate_Label;
extern const std::string STC_Letter_Received_Label;
extern const std::string STC_Expiry_Date_Label;
extern const std::string CAE_Casual_Agricultural_Employee_Label;
extern const std::string EDW_Election_Day_Worker_Label;
extern const std::string NSW_Non_Resident_Seasonal_Worker_Label;
extern const std::string WT_Schedular_Payments_Contractors_Label;
// PAYE Tax Labels
extern const std::string PAYE_Tax_Label;
extern const std::string Gross_Earnings_Label;
extern const std::string NET_Pay_Label;
extern const std::string Total_Days_Label;
extern const std::string Total_Days_In_Hour_Format_Label;
extern const std::string Travel_Allowance_Label;
extern const std::string Meal_Allowance_Label;
extern const std::string Tool_Allowance_Label;
extern const std::string Clothing_Uniform_Allowance_Label;
extern const std::string On_Call_Shift_Lump_Sum_Label;
extern const std::string Backpay_Lump_Sum_Label;
extern const std::string Backpay_Dates_Label;
extern const std::string Cash_Gift_Lump_Sum_Label;
extern const std::string Commission_Lump_Sum_Label;
extern const std::string Total_Decimal_Amount_$_Label;
extern const std::string Public_Holidays_Label;
extern const std::string Sick_Leave_Label;
extern const std::string Annual_Leave_Label;
extern const std::string Parental_Leave_Label;
extern const std::string Special_Leave_Label;
extern const std::string Total_Sick_Days_Label;
extern const std::string Total_Annual_Leave_Days_Label;
extern const std::string Total_Parent_Leave_Days_Label;
extern const std::string Total_Unpaid_Leave_Days_Label;
extern const std::string Total_Paid_Overtime_Hours_Label;
extern const std::string Total_Unpaid_Overtime_Hours_Label;
extern const std::string Total_Allowance_Payment_s_Label;
extern const std::string Total_Lump_Sum_Payment_s_Label;
extern const std::string Total_Employee_Benefits_Contributions_from_Employer_Label;
extern const std::string Total_Employee_Voluntary_Contributions_Deductions_Label;
extern const std::string Total_Taxable_Deductions_Label;
extern const std::string Remainder_Leave_Balances_Label;
extern const std::string Remainder_PDC_Balances_Label;
extern const std::string Remainder_EAP_Balances_Label;
extern const std::string Request_Label;
extern const std::string Parental_Leave_Type_Label;
extern const std::string Maternity_Leave_Label;
extern const std::string Paternity_Leave_Label;
extern const std::string Adoptive_Parent_Leave_Label;
extern const std::string Shared_Parent_Leave_Label;
extern const std::string Start_Date_Label;
extern const std::string End_Date_Label;
extern const std::string Enter_Start_Date_Label;
extern const std::string Enter_End_Date_Label;
extern const std::string Enter_Brief_Reason_Description_Label;

extern const std::string Received_Label;
extern const std::string Approved_Label;
extern const std::string Denied_Label;
extern const std::string Temp_Denied_Label;
extern const std::string Reason_Label;
extern const std::string Needs_More_Info_Label;
extern const std::string Popular_Leave_Time_Label;
extern const std::string Shift_Conflict_Label;
extern const std::string No_Leave_Balance_Remaining_Label;
extern const std::string Scheduling_Requirements_Currently_Unmet_Label;
extern const std::string Set_Rules_for_Leave_Request_Label;
extern const std::string Waiting_for_Other_Info_Label;
extern const std::string Does_Not_Met_Other_Leave_Criteria_Label;

extern const std::string Open_Label;
extern const std::string Resolved_Label;
extern const std::string Reopen_Label;
extern const std::string For_Approval_Label;
extern const std::string For_Full_Denial_Label;


#endif // FORM_LABELS_UI_H
